version: '3.7'

services: 
  web:
    image: nginx:alpine
    volumes:
      - ./nginix.conf:/etc/nginx/nginx.conf
    ports: 
      - 11031:80
    networks: 
      - app1_net
      - app2_net
  app1:
    image: httpd:latest
    networks: 
      - app1_net
  app2:
    image: httpd:latest
    networks: 
      - app2_net
networks: 
  app1_net:
  app2_net:
